language: python
os: linux
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -U setuptools setuptools_scm tox-travis codecov"
# command to run tests
script:
  - tox
  - sed -i 's/filename="/filename=".\//g' coverage.xml
  - ( which sonar-scanner && sonar-scanner || true )
after_success:
  - codecov
